# Generated by Django 5.1 on 2024-08-29 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.RegexValidator(message="Номер телефона необходимо ввести в формате: '+996xxxxxxxxx'.", regex='^\\+996\\d{9}$')], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
