# Generated by Django 5.1 on 2024-09-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
