# Generated by Django 5.1 on 2024-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
