# Generated by Django 5.1 on 2024-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=1, max_length=50, verbose_name='Подтверждения пароля'),
            preserve_default=False,
        ),
    ]
