# Generated by Django 5.1 on 2024-08-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_phone_number_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
